### ISSUE TITLE
Help With Download Progress

### ISSUE THREAD

**Issue by david-littlefield** [PeerGroupSoftware/Youtube-To-Mac#4]

**Comment by Jake3231** [comment]
Hi, sorry we didn't get back to you sooner! I'm very happy to hear that you've enjoyed using YoutubeToMac!

In your app, are you executing the youtube-DL executable using `Process` (formerly `NSTask`)? In YoutubeToMac, a download `Process` is created, then a function is called that sets the `Process`'s `standardOutput` property to a new `Pipe`. I'd encourage you to look at the `captureStandardOutput()` function in the Downloader.swift file on YoutubeToMac's 1.2.0 branch.

```
outputPipe = Pipe()
task.standardOutput = outputPipe
        
outputPipe.fileHandleForReading.waitForDataInBackgroundAndNotify()
        
NotificationCenter.default.addObserver(forName: NSNotification.Name.NSFileHandleDataAvailable, object: outputPipe.fileHandleForReading , queue: nil) {
notification in
            
let output = self.outputPipe.fileHandleForReading.availableData
let outputString = String(data: output, encoding: String.Encoding.utf8) ?? ""
}
```

I'd be happy to provide some tips if there's a particular part of the code that is not working, or if you're seeing an error.

**Comment by david-littlefield** [comment]
Hi @Jake3231, thanks for getting back! Sorry, I may have sent the wrong impression. I closed the issue because I figured out how to solve the problem, haha.

I completed the Python 3 course from Codecademy, which was totally worth it. And, the issue ended up being that the Python code only sent progress updates to standard output when a downloaded started and finished.

Then, I modified the example from `youtube-dl` to send progress update to standard output while downloading. Then, it printed my custom progress updates to the command line interface. 

Then, I found a Python executable converter, converted the `youtube-dl` directory, and loaded it into XCode.

And now, I'm setting everything up on the Swift-side. I'll find out whether Swift receives the new progress updates very soon. I'm also thinking about how I can improve my user interface based on your awesome design. =]

**Comment by Jake3231** [comment]
Good to hear that you were able to solve the problem! Please let me know if you run into any other Swift related issues, or if I can do anything else to help regarding your app.

It’s great to hear that YoutubeToMac has been a source of inspiration for your user interface!

Feel free to contact us at [@Peer_Software](https://twitter.com/Peer_Software) or peergroupsoftware@gmail.com
