### ISSUE TITLE
"Could not save audio" error

### ISSUE THREAD

**Issue by Mennaruuk** [PeerGroupSoftware/Youtube-To-Mac#6]
![Screen Shot 2020-11-07 at 10 52 13 PM](https://user-images.githubusercontent.com/52135169/98456466-0892c680-214c-11eb-89dd-60315382d113.png)

```
Could not save audio
The requested format is not available for this content, please use the automatic format selection.
```
I tried with multiple videos and non-auto formats. Only auto works. I noticed the same issue [popped up back in mid-2019](https://github.com/PeerGroupSoftware/Youtube-To-Mac/issues/2#issuecomment-507691744).

**Comment by Jake3231** [comment]
Thanks for reporting this issue. Currently, the format selector requests the selected format from the content website, and does not work if the website doesn't already have that format available. I'm looking into ways for YoutubeToMac to convert some formats to the requested format, though.

**Comment by Jake3231** [comment]
@Mennaruuk As an update, I've so far had promising results with addressing this issue. I hope to publish a beta update that addresses this issue.

**Comment by Mennaruuk** [comment]
Appreciate your help! It’s a neat little software that can do so much, and I like that I can use it over the terminal. Hopefully the beta update resolves these issues.

**Comment by Mennaruuk** [comment]
Thank you for resolving these issues 🙏

**Comment by Jake3231** [comment]
Sure! I hope that I can soon have the 1.3.0 branch polished enough to push this feature out to a beta release.
